version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install cfn-lint
  build:
    commands:
      - echo "Validating CloudFormation templates..."
      - cfn-lint -i W -t infra/infra-template.json || exit 1
      - aws cloudformation validate-template --template-body file://infra/infra-template.json
artifacts:
  files:
    - '**/*'
  discard-paths: no

